columns_to_use : ['target',
                  'TaxaDeUtilizacaoDeLinhasNaoGarantidas',
                  'Idade',
                  'NumeroDeVezes30-59DiasAtrasoNaoPior',
                  'TaxaDeEndividamento',
                  'RendaMensal',
                  'NumeroDeLinhasDeCreditoEEmprestimosAbertos',
                  'NumeroDeVezes90DiasAtraso',
                  'NumeroDeEmprestimosOuLinhasImobiliarias',
                  'NumeroDeVezes60-89DiasAtrasoNaoPior',
                  'NumeroDeDependentes']

train_dataset_name : 'train.csv'
test_dataset_name : 'test.csv'

target_name : 'target'
t_size : 0.2
r_state : 42

vars_imputer : ['RendaMensal', 
                'NumeroDeDependentes'] 
vars_discritiser : ['TaxaDeUtilizacaoDeLinhasNaoGarantidas',
                    'TaxaDeEndividamento',
                    'RendaMensal']

model_name : 'model.joblib'

app_name : "prob_load_sagemaker"
arn : "arn:aws:iam::758422541987:role/sagemaker_func"
image_ecr_uri : ""
region : 'us-east-1'

model_uri : 'C:\Servidor\OneDrive - CALCADOS BEIRA RIO S A\Documentos\repos\mlflow\mlartifacts\1\822ff65cf0da436590fc9e0fadecd697\artifacts\model.joblib'